### ISSUE TITLE
Broken methods & formatting errors

### ISSUE THREAD

**Issue by dcelasun** [laravelbook/laravel4-phpstorm-helper#4]
There are lots of broken methods in this helper. For example on line `503`:

```
 * @method   static void    make(string  $view, array   $data)  Get a evaluated view contents for the given view.
```

This line is wrong because:
- It's return type is `View` not `void`
- The `$data` array is optional

Similarly, there are other broken methods:

```
Line 45-48, 63-66: Declaration must be compatible with ArrayAccess->offsetExists($offset)
Line 50:  Extending abstract class without implementing abstract methods
Line 90-95: ConnectionInterface problems
Line 249-252: Namespace \Illuminate\Foundation is unresolved
Line 295-296, 328-329: Undefined class dynamic
```

There are other lines with these problems, but they all have one of these errors.

Finally, the file uses tabs instead of spaces ( _why?!?_ ) so formatting is broken.

**Comment by niallobrien** [comment]
Fix and submit a pull req.
